<a href="https://colab.research.google.com/github/Haferkorn/DataScience_Portfolio/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercise 1**: from 101 Numpy Exercises: Import numpy as np and see the version

In [ ]:
import numpy as np
print(np.__version__)

1.19.5


**Exercise 2**: from 101 Numpy Exercises: How to create a 1D array?

In [ ]:
list=[1,2,3,4,5]
arrd1=np.array(list)
#or
a = np.array([1,2,3,4,5], dtype='int32')
print(type(arrd1))
print(arrd1)
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]
[1 2 3 4 5]


**Exercise 3:** from 101 Numpy Exercises: How to create a boolean array? 
Q. Create a 3×3 numpy array of all True’s


In [ ]:


list2=[[True],[True],[True]]
arrd3=np.array(list2)
# Or 
arr1d= np.full((3, 3), True, dtype=bool)

print(arrd3)

[[ True]
 [ True]
 [ True]]


**Exercise 4:**  How to extract items that satisfy a given condition from 1D array? Q. Extract all odd numbers from arr

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr2=arr[arr % 2 == 1]
print(arr)


[0 1 2 3 4 5 6 7 8 9]


**Exercise 5:** How to replace items that satisfy a condition with another value in numpy array?  Replace all odd numbers in arr with -1

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[arr % 2 == 1] = -1

print(arr)

[-1  2 -1  4 -1  6 -1  8 -1 10]


**Exercise 6**: How to replace items that satisfy a condition without affecting the original array?

Q. Replace all odd numbers in arr with -1 without changing *arr*

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
out = np.where(arr % 2 == 1, -1, arr)
print(arr)
print(out)

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  2  3  4  3  6  3  8  3 10]


**Exerice 7**: How to reshape an array?

Q. Convert a 1D array to a 2D array with 2 rows

In [ ]:
arr.shape
arrd2=arr.reshape(2,-1)
print(arrd2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


**Exercise 8: ** How to stack two arrays vertically? 
Q. Stack arrays a and b vertically

In [ ]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**Exercise 9** :How to stack two arrays horizontally? Stack the arrays a and b horizontally.

In [ ]:
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

**Exercise 10**: How to generate custom sequences in numpy without hardcoding? Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

In [ ]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]
             

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

**Exercise 11** : How to get the common items between two python numpy arrays? Get the common items between a and b

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

**Exercise 12**: How to remove from one array those items that exist in another?

In [ ]:
# From 'a' remove all of 'b'
np.setdiff1d(a,b)

array([1, 3, 5, 6])

**Exercise 13**: How to get the positions where elements of two arrays match?

In [ ]:
np.where(a == b)

(array([1, 3, 5, 7]),)

**Exercise 14**: How to extract all numbers between a given range from a numpy array?

In [ ]:
c=np.arange(15)
index = np.where(np.logical_and(c>=5, c<=10))
c[index]

array([ 5,  6,  7,  8,  9, 10])

**Exercise 15**: How to make a python function that handles scalars to work on numpy arrays?

In [ ]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

pair_max = np.vectorize(maxx, otypes=[float])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max(a, b)

**Exercise 16**: How to swap two columns in a 2d numpy array?

In [ ]:
# Input
arr = np.arange(9).reshape(3,3)
arr

# Solution
arr[:, [1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

**Exercise 17**: How to swap two rows in a 2d numpy array?

In [ ]:
# Input
arr = np.arange(9).reshape(3,3)

# Solution
arr[[1,0,2], :]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

**Exercise 18**: How to reverse the rows of a 2D array?

In [ ]:
# Input
arr = np.arange(9).reshape(3,3)

# Solution
arr[::-1]

**Exercise 19**: How to reverse the columns of a 2D array?

In [ ]:
# Input
arr = np.arange(9).reshape(3,3)

# Solution
arr[:, ::-1]

**Exercise 20**: How to create a 2D array containing random floats between 5 and 10?

In [ ]:
arr = np.arange(9).reshape(3,3)

# Solution Method 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))

**Exercise 21**:  How to print only 3 decimal places in python numpy array?

In [ ]:
# Input
rand_arr = np.random.random((5,3))

# Create the random array
rand_arr = np.random.random([5,3])

# Limit to 3 decimal places
np.set_printoptions(precision=3)
rand_arr[:4]

array([[0.3  , 0.907, 0.785],
       [0.731, 0.751, 0.05 ],
       [0.072, 0.869, 0.996],
       [0.472, 0.737, 0.279]])

**Exercise 22**: How to pretty print a numpy array by suppressing the scientific notation (like 1e10)?

In [ ]:
# Reset printoptions to default
np.set_printoptions(suppress=False)

# Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

**Exercise 23**: How to limit the number of items printed in output of numpy array?

In [ ]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

**Exercise 24**: How to print the full numpy array without truncating

In [ ]:
# Input
np.set_printoptions(threshold=6)
a = np.arange(15)

# Solution
np.set_printoptions(threshold=np.nan)
a

**Exercise 25**: How to import a dataset with numbers and texts keeping the text intact in python numpy?

In [ ]:
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)